controller_manager:
  ros__parameters:
    update_rate: 80

    position_forw_arm_controller:
      type:  position_controllers/JointGroupPositionController

    position_forw_gripper_controller:
      type:  position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_forw_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    interface_name: position   # ForwardCommandController uses singular "interface_name"

position_forw_gripper_controller:
  ros__parameters:
    joints:
      - right_gear_joint
    interface_name: position

joint_state_broadcaster:
  ros__parameters:
    update_rate: 100
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - right_gear_joint
    interfaces:
      - position
      - velocity
      - effort
