controller_manager:
  ros__parameters:
    update_rate: 80

    position_arm_controller:   
      type: joint_trajectory_controller/JointTrajectoryController

    position_gripper_controller:  
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    #allow_integration_in_goal_trajectories: true
    open_loop_control: false

    constraints:
      #goal_time: 10.0  # Wait up to 2 seconds for goal completion
      stopped_velocity_tolerance: 0.0001  # Robot should stop within this velocity range
      #goal_tolerance: 0.01  # How close the joints should get to the target before MoveIt! accepts success

    

position_gripper_controller:
  ros__parameters:
    joints:
      - gear1_joint
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      gear1_joint: {p: 1.5, i: 0.0, d: 0.0, angle_wraparound: true}

    open_loop_control: false
    allow_integration_in_goal_trajectories: true

joint_state_broadcaster:
  ros__parameters:
    update_rate: 100
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - gear1_joint

    # joints:
    #   - joint_5
    #   - joint_6
    #   - joint_7
    
    interfaces:
      - position
      - velocity
      - effort