controller_manager:
  ros__parameters:
    update_rate: 10

    velocity_arm_controller: # original controller   
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_gripper_controller: # original controller   
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      joint_1:
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
    
      joint_2:  # Joint 2 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false     

      joint_3:  # Joint 3 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false

      joint_4:  # Joint 4 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false

      joint_5:  # Joint 5 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false

      joint_6:  # Joint 6 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false

      joint_7:  # Joint 7 PID gains
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        antiwindup: false

    #allow_integration_in_goal_trajectories: true
    open_loop_control: false

    constraints:
      #goal_time: 10.0  # Wait up to 2 seconds for goal completion
      stopped_velocity_tolerance: 0.001  # Robot should stop within this velocity range
      #goal_tolerance: 0.01  # How close the joints should get to the target before MoveIt! accepts success

    

velocity_gripper_controller:
  ros__parameters:
    joints:
      - gear1_joint
    command_interfaces: 
      - velocity
    state_interfaces:
      - position
      - velocity

    gains:
      gear1_joint: {p: 30.0, i: 0.0, d: 0.0, angle_wraparound: true}

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
