default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_4:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  joint_7:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15

  gear1_joint:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  base_claw_joint1:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  claw_joint1:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  gear2_joint:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  base_claw_joint2:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15
  claw_joint2:
    has_velocity_limits: true
    max_velocity: 1.35
    has_acceleration_limits: true
    max_acceleration: 1.15