/**:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - velocity_arm_controller
        - velocity_gripper_controller

      velocity_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: True
        joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
          - joint_7

      velocity_gripper_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: True
        joints:
          - gear1_joint
          - base_claw_joint1
          - base_claw_joint2
          - claw_joint1
          - gear2_joint
          - claw_joint2

    trajectory_execution:
      allowed_execution_duration_scaling: 12.0  # Allows execution to take twice the estimated time
      execution_duration_monitoring: true  # Must be a boolean
      allowed_goal_duration_margin: 3.0  # Extra margin for goal completion

    
