from setuptools import find_packages, setup

package_name = 'some_examples_py'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='maryam-mahmood',
    maintainer_email='maryam-mahmood@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'simple_publisher = some_examples_py.simple_publisher:main',
            'my_action_server = some_examples_py.my_action_server:main',
            'gui_trajectory = some_examples_py.gui_trajectory:main',
            'gui_trajectory_2 = some_examples_py.gui_trajectory_2:main',
            'sim_driver = some_examples_py.sim_driver:main',
            'gui_trajectory_3 = some_examples_py.gui_trajectory_3:main',
            'mpipe = some_examples_py.mpipe:main',
            'z_torque_aggregator = some_examples_py.z_torque_aggregator:main',
            'rviz_torque_text = some_examples_py.rviz_torque_text:main', 
            'tf_visualizer = some_examples_py.tf_visualizer:main',
            'ctc_controller = some_examples_py.ctc_controller:main',
            'ctc_gui_ros = some_examples_py.ctc_gui_ros:main',
            'collect_data = some_examples_py.collect_data:main',
            'train_dynamics = some_examples_py.train_dynamics:main',
            'quantile_error = some_examples_py.quantile_error:main',
            'ctc_node = some_examples_py.ctc_node:main',
            'CRCLF = some_examples_py.CRCLF:main',
            'compare_clf = some_examples_py.compare_clf:main',
            'IK_traj = some_examples_py.IK_traj:main',
            'circle_IK = some_examples_py.circle_IK:main',
            'ellipse_IK = some_examples_py.ellipse_IK:main',
            'elliptical_data = some_examples_py.elliptical_data:main',
            'train_ellipse_dynamics = some_examples_py.train_ellipse_dynamics:main',
            'clf_oper = some_examples_py.clf_oper:main',
            # 'robot_dynamics = some_examples_py.robot_dynamics:main',
            # 'resclf_formulation = some_examples_py.resclf_formulation:main',
            # 'qp_solver = some_examples_py.qp_solver:main',
            'main_controller = some_examples_py.CLF_CBF_traj.main_controller:main',
            'cr_main_controller = some_examples_py.CRCLF_CRCBF_traj.cr_main_controller:main',
            # 'crclf_formulation = some_examples_py.CRCLF_CRCBF_traj.crclf_formulation:main',
            # 'crcbf_formulation = some_examples_py.CRCLF_CRCBF_traj.crcbf_formulation:main',
            # 'crqp_solver = some_examples_py.CRCLF_CRCBF_traj.crqp_solver:main',
            'collect_calibration_data = some_examples_py.CRCLF_CRCBF_traj.collect_calibration_data:main',
            'compare_controllers_robust = some_examples_py.CRCLF_CRCBF_traj.compare_controllers_robust:main',
            'main_node = some_examples_py.CLF_CBF.main_node:main',
            'cr_main_node = some_examples_py.CRCLF_CRCBF.cr_main_node:main',
            'trajectory_visualizer = some_examples_py.CLF_CBF.trajectory_visualizer:main',
            'safety_visualizer = some_examples_py.CLF_CBF.safety_visualizer:main',
            'compare_robust = some_examples_py.CRCLF_CRCBF.compare_robust_models:main',
            'pinocchio_main_node = some_examples_py.CLF_CBF.pinocchio_main_node:main',
            'cr_pinocchio_main = some_examples_py.CRCLF_CRCBF.cr_pinocchio_main:main',
            'main_2_link = some_examples_py.CLF_CBF_2_link.main_node:main',
            'pinocchio_main_node_2_link = some_examples_py.CLF_CBF_2_link.pinocchio_main_node:main',
            'trajectory_visualizer_2_link = some_examples_py.CLF_CBF_2_link.trajectory_visualizer:main',
            'safety_visualizer_2_link = some_examples_py.CLF_CBF_2_link.safety_visualizer:main',
            'cr_main_2_link = some_examples_py.CRCLF_CRCBF_2_link.main_node:main',
            'cr_pinocchio_main_2_link = some_examples_py.CRCLF_CRCBF_2_link.pinocchio_main_node:main',
            'pinocchio_main_2_link = some_examples_py.CLF_CBF_2_link.pinocchio_main_node:main',
            'quantile_data = some_examples_py.CRCLF_CRCBF_2_link.quantile_data:run_pipeline'
        ],
    },
)
